# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: iOS-ipa-build

on:
  workflow_dispatch:

  
jobs:
  build-ios:
    name: 🎉 iOS Build
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS dependencies
        run: pod install --repo-update
        working-directory: ios

      - name: Build iOS app without signing
        run: xcodebuild archive -workspace ios/NewProject.xcworkspace -scheme NewProject -configuration Release -sdk iphoneos -archivePath $PWD/build/NewProject.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Export .ipa file without signing
        run: xcodebuild -exportArchive -archivePath $PWD/build/NewProject.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Rename .ipa file
        run: mv build/NewProject.ipa build/ReactNativeIpaExport.ipa

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ReactNativeIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"

